// <auto-generated />
using System;
using CarLogBook.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarLogBook.Infrastructure.Migrations
{
    [DbContext(typeof(CarLogBookDbContext))]
    [Migration("20260215095127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("CarLogBook.Domain.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarLogBook.Domain.FuelEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FuelStationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FuelStationId1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FuelTypeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFullTank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("FuelStationId");

                    b.HasIndex("FuelStationId1");

                    b.HasIndex("FuelTypeId");

                    b.ToTable("FuelEntries");
                });

            modelBuilder.Entity("CarLogBook.Domain.FuelStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FuelStations");
                });

            modelBuilder.Entity("CarLogBook.Domain.FuelType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");
                });

            modelBuilder.Entity("CarLogBook.Domain.MaintenanceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceCategories");
                });

            modelBuilder.Entity("CarLogBook.Domain.MaintenanceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MaintenanceCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MaintenanceCategoryId");

                    b.ToTable("MaintenanceEvents");
                });

            modelBuilder.Entity("CarLogBook.Domain.FuelEntry", b =>
                {
                    b.HasOne("CarLogBook.Domain.Car", null)
                        .WithMany("FuelEntries")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarLogBook.Domain.FuelStation", null)
                        .WithMany("FuelEntries")
                        .HasForeignKey("FuelStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarLogBook.Domain.FuelStation", "FuelStation")
                        .WithMany()
                        .HasForeignKey("FuelStationId1");

                    b.HasOne("CarLogBook.Domain.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CarLogBook.Domain.Money", "Cost", b1 =>
                        {
                            b1.Property<Guid>("FuelEntryId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("CostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("CostCurrency");

                            b1.HasKey("FuelEntryId");

                            b1.ToTable("FuelEntries");

                            b1.WithOwner()
                                .HasForeignKey("FuelEntryId");
                        });

                    b.OwnsOne("CarLogBook.Domain.OdometerReading", "Odometer", b1 =>
                        {
                            b1.Property<Guid>("FuelEntryId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Kilometers")
                                .HasColumnType("TEXT")
                                .HasColumnName("OdometerKilometers");

                            b1.HasKey("FuelEntryId");

                            b1.ToTable("FuelEntries");

                            b1.WithOwner()
                                .HasForeignKey("FuelEntryId");
                        });

                    b.OwnsOne("CarLogBook.Domain.FuelVolume", "Volume", b1 =>
                        {
                            b1.Property<Guid>("FuelEntryId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Liters")
                                .HasColumnType("TEXT")
                                .HasColumnName("VolumeLiters");

                            b1.HasKey("FuelEntryId");

                            b1.ToTable("FuelEntries");

                            b1.WithOwner()
                                .HasForeignKey("FuelEntryId");
                        });

                    b.Navigation("Cost");

                    b.Navigation("FuelStation");

                    b.Navigation("FuelType");

                    b.Navigation("Odometer");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("CarLogBook.Domain.MaintenanceEvent", b =>
                {
                    b.HasOne("CarLogBook.Domain.Car", null)
                        .WithMany("MaintenanceEvents")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarLogBook.Domain.MaintenanceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarLogBook.Domain.MaintenanceCategory", null)
                        .WithMany("MaintenanceEvents")
                        .HasForeignKey("MaintenanceCategoryId");

                    b.OwnsOne("CarLogBook.Domain.Money", "Cost", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceEventId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT")
                                .HasColumnName("CostAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("CostCurrency");

                            b1.HasKey("MaintenanceEventId");

                            b1.ToTable("MaintenanceEvents");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceEventId");
                        });

                    b.OwnsOne("CarLogBook.Domain.OdometerReading", "Odometer", b1 =>
                        {
                            b1.Property<Guid>("MaintenanceEventId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Kilometers")
                                .HasColumnType("TEXT")
                                .HasColumnName("OdometerKilometers");

                            b1.HasKey("MaintenanceEventId");

                            b1.ToTable("MaintenanceEvents");

                            b1.WithOwner()
                                .HasForeignKey("MaintenanceEventId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Cost");

                    b.Navigation("Odometer");
                });

            modelBuilder.Entity("CarLogBook.Domain.Car", b =>
                {
                    b.Navigation("FuelEntries");

                    b.Navigation("MaintenanceEvents");
                });

            modelBuilder.Entity("CarLogBook.Domain.FuelStation", b =>
                {
                    b.Navigation("FuelEntries");
                });

            modelBuilder.Entity("CarLogBook.Domain.MaintenanceCategory", b =>
                {
                    b.Navigation("MaintenanceEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
